[package]
name = "dapi-client-rust"
version = "0.1.0"
authors = ["10xcryptodev <10xcryptodev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
